"""fix owner and parking lot relationship2

Revision ID: c71ee4602fa7
Revises: e2d4305c64bb
Create Date: 2025-08-18 15:27:04.932314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71ee4602fa7'
down_revision: Union[str, Sequence[str], None] = 'e2d4305c64bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
